site_name: 🪙 Cost of Living
site_description: Cost of living in 26 European countries and 120+ cities
site_author: Alcatelz
site_url: https://designrpros.github.io/costofliving/

google_analytics:
  - G-KCYT87ZMVZ
  - auto

theme:
  name: material
  palette:
    primary: teal
    accent: cyan
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.expand

plugins:
  - search:
      separator: '[\s\-\.]+'
      prebuild_index: true

nav:
  - 🏔️ Northern Europe:
    - norway/overview.md
    - sweden/overview.md
    - denmark/overview.md
    - estonia/overview.md
    - iceland/overview.md
    - finnland/overview.md
  - 🏗️ Eastern Europe:
    - poland/overview.md
    - czech/overview.md
    - hungary/overview.md
    - romania/overview.md
    - serbia/overview.md
    - bulgaria/overview.md
  - ☀️ Southern Europe:
    - spain/overview.md
    - portugal/overview.md
    - italy/overview.md
    - greece/overview.md
    - croatia/overview.md
    - malta/overview.md
  - 🔵 Central Europe:
    - germany/overview.md
    - austria/overview.md
    - switzerland/overview.md
  - 🌊 Western Europe:
    - uk/overview.md
    - ireland/overview.md
    - netherlands/overview.md
    - belgium/overview.md
    - france/overview.md
  - 💰 Affiliate: affiliate.md
  - 🛠️ Practical: praktisk/index.md
  - 🌍 Links: europe-links.md
